# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleicao',
            name='secretario',
        ),
        migrations.AddField(
            model_name='eleitor',
            name='email',
            field=models.EmailField(default='nome@mail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Secretario',
        ),
    ]
